version: '3.8'

services:
  postgres-db:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abhaveda
      POSTGRES_DB: testDB
    ports:
      - "5433:5432"
    networks:
      - my-network

  spring-app:
    build: .
    container_name: spring-app
    depends_on:
      - postgres-db
    ports:
      - "8081:8081"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge